import Head from "next/head";
import styles from "../styles/common.module.css";
import style from "../styles/frame7.module.css";
import Banner from "../components/banner";
import BlogSection from "../components/Locations";
import DesinationCard from "../components/DestinationCard";
import Holiday from "../components/Holidaycard";
import Layout from "../components/Layout";
import Button from "../components/Button";
import Places from "../components/Places";
import PillSection from "../components/PillSection";
import OfferSection from "../components/OfferSection";

const blogList = [
  {
    img: "/img/blog.png",
    text: "1 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "2 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "3 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "4 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "5 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "6 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "7 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "8 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "9 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
  {
    img: "/img/blog.png",
    text: "10 Najlepsze hotele z Aquaparkami w Hiszpani",
  },
];

const pillsList = [
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
  {
    pillLink: "#",
    pilltext: "Wakacje w styczniu",
  },
];

export default function Home() {
  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="container wd">
          <Banner />
          <div className="row my-4">
            <h3 className="my-5">Szukaj miejsca na wakacje</h3>
            <div className="col-lg-8 col-md-12 my-2">
              <DesinationCard />
            </div>
            <div className="col-lg-4 col-md-12 my-2">
              <Holiday />
            </div>
          </div>
          <div className="row">
            <div className="col-lg-8 col-md-12 pr-0">
              <div className="row my-2">
                {blogList?.map((item, index) => (
                  <div key={index} className="col-lg-6 col-md-12">
                    <BlogSection item={item} />
                  </div>
                ))}
              </div>
              <div className="row mb-5">
                <div className="col-lg-12">
                  <Button />
                </div>
              </div>
            </div>
          </div>
          <h3 className="py-5">Często wyszukiwana pogoda</h3>
          <div className={style.multi__col}>
            <Places />
            <Places />
            <Places />
            <Places />
            <Places />
            <Places />
            <Places />
            <Places />
            <Places />
          </div>
        </section>
        <div className="container wd">
          <div className="my-5">
            <div className="row">
              <div className="col-lg-12">
                <div className={styles.pills__title}>
                  <h3>Sprawdź gdzie jechać na wakacje</h3>
                </div>
                <div className={styles.pills__div}>
                  {pillsList.map((item, index) => (
                    <PillSection item={item} key={index} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container wd">
          <div className="my-5">
            <h3 className="mb-5">Gorące oferty Last Minute</h3>
            <div className="row">
              <OfferSection />
              <OfferSection />
              <OfferSection />
              <OfferSection />
            </div>
            <div className="row">
              <div className="col-lg-12">
                <Button />
              </div>
            </div>
          </div>
        </div>
      </>
    </Layout>
  );
}
